AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  Exclude:
    - db/migrate/**

Style/StringLiterals:
  Enabled: false

Style/TrailingCommaInLiteral:
  Description: 'Checks for trailing comma in array and hash literals.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#no-trailing-array-commas'
  EnforcedStyleForMultiline: 'comma'

Style/TrailingCommaInArguments:
  Description: 'Checks for trailing comma in arguments.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#no-trailing-params-comma'
  EnforcedStyleForMultiline: 'comma'

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: new_line
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Naming/FileName:
  Enabled: false

Layout/AlignParameters:
  Enabled: false

Layout/ClosingParenthesisIndentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 250

Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"

Style/Documentation:
    Enabled: false

Lint/Void:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Layout/IndentArray:
  Enabled: true
  EnforcedStyle: consistent

# Multi-line method chaining should be done with leading dots.
Layout/DotPosition:
  EnforcedStyle: leading
  SupportedStyles:
    - leading
    - trailing

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
  SupportedStyles:
    - aligned
    - indented

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
  SupportedStyles:
    - aligned
    - indented

Style/LineEndConcatenation:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method
  SupportedStyles:
    - prefer_alias
    - prefer_alias_method

Style/NumericLiterals:
  Enabled: false

Style/SignalException:
  EnforcedStyle: semantic

Performance/Casecmp:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
